server:
  port: 8003
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/seata?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: system

mybatis-plus:
  mapper-locations:
    - classpath*:com/codeman/**/xml/*Mapper.xml
    - classpath:mapper/*.xml
    - classpath:dao/*.xml